<?xml version="1.0" encoding="utf-8"?><Database Name="CriminalFinderDatabase" Class="CriminalDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-C7Q3MLK\SQLEXPRESS;Initial Catalog=CriminalFinderDatabase;Integrated Security=True" SettingsObjectName="CriminalFinder.BusinessLayer.Properties.Settings" SettingsPropertyName="CriminalFinderDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CriminalInfoTable" Member="CriminalInfoTables">
    <Type Name="CriminalInfoTable">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>