//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalFinder.WebClient.UnitTest.CriminalWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalWS.ICriminalService")]
    public interface ICriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminals", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalsResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse GetCriminals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminals", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalsResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> GetCriminalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchCriminals", ReplyAction="http://tempuri.org/ICriminalService/SearchCriminalsResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse SearchCriminals(CriminalFinder.WebClient.CriminalFinderService.CriminalSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchCriminals", ReplyAction="http://tempuri.org/ICriminalService/SearchCriminalsResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> SearchCriminalsAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminal", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse GetCriminal(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminal", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> GetCriminalAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/UpdateCriminal", ReplyAction="http://tempuri.org/ICriminalService/UpdateCriminalResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse UpdateCriminal(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/UpdateCriminal", ReplyAction="http://tempuri.org/ICriminalService/UpdateCriminalResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> UpdateCriminalAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/CreateCriminal", ReplyAction="http://tempuri.org/ICriminalService/CreateCriminalResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse CreateCriminal(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/CreateCriminal", ReplyAction="http://tempuri.org/ICriminalService/CreateCriminalResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> CreateCriminalAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/DeleteCriminal", ReplyAction="http://tempuri.org/ICriminalService/DeleteCriminalResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse DeleteCriminal(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/DeleteCriminal", ReplyAction="http://tempuri.org/ICriminalService/DeleteCriminalResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> DeleteCriminalAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/DeleteCriminals", ReplyAction="http://tempuri.org/ICriminalService/DeleteCriminalsResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse DeleteCriminals(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo[] criminalList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/DeleteCriminals", ReplyAction="http://tempuri.org/ICriminalService/DeleteCriminalsResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> DeleteCriminalsAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo[] criminalList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/QuickSearchCriminalsByName", ReplyAction="http://tempuri.org/ICriminalService/QuickSearchCriminalsByNameResponse")]
        CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse QuickSearchCriminalsByName(string searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/QuickSearchCriminalsByName", ReplyAction="http://tempuri.org/ICriminalService/QuickSearchCriminalsByNameResponse")]
        System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> QuickSearchCriminalsByNameAsync(string searchCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriminalServiceChannel : CriminalFinder.WebClient.UnitTest.CriminalWS.ICriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriminalServiceClient : System.ServiceModel.ClientBase<CriminalFinder.WebClient.UnitTest.CriminalWS.ICriminalService>, CriminalFinder.WebClient.UnitTest.CriminalWS.ICriminalService {
        
        public CriminalServiceClient() {
        }
        
        public CriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse GetCriminals() {
            return base.Channel.GetCriminals();
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> GetCriminalsAsync() {
            return base.Channel.GetCriminalsAsync();
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse SearchCriminals(CriminalFinder.WebClient.CriminalFinderService.CriminalSearchCriteria searchCriteria) {
            return base.Channel.SearchCriminals(searchCriteria);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> SearchCriminalsAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalSearchCriteria searchCriteria) {
            return base.Channel.SearchCriminalsAsync(searchCriteria);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse GetCriminal(long id) {
            return base.Channel.GetCriminal(id);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> GetCriminalAsync(long id) {
            return base.Channel.GetCriminalAsync(id);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse UpdateCriminal(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal) {
            return base.Channel.UpdateCriminal(criminal);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> UpdateCriminalAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal) {
            return base.Channel.UpdateCriminalAsync(criminal);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse CreateCriminal(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal) {
            return base.Channel.CreateCriminal(criminal);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> CreateCriminalAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo criminal) {
            return base.Channel.CreateCriminalAsync(criminal);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse DeleteCriminal(long id) {
            return base.Channel.DeleteCriminal(id);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> DeleteCriminalAsync(long id) {
            return base.Channel.DeleteCriminalAsync(id);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse DeleteCriminals(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo[] criminalList) {
            return base.Channel.DeleteCriminals(criminalList);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> DeleteCriminalsAsync(CriminalFinder.WebClient.CriminalFinderService.CriminalInfo[] criminalList) {
            return base.Channel.DeleteCriminalsAsync(criminalList);
        }
        
        public CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse QuickSearchCriminalsByName(string searchCriteria) {
            return base.Channel.QuickSearchCriminalsByName(searchCriteria);
        }
        
        public System.Threading.Tasks.Task<CriminalFinder.WebClient.CriminalFinderService.CriminalServiceResponse> QuickSearchCriminalsByNameAsync(string searchCriteria) {
            return base.Channel.QuickSearchCriminalsByNameAsync(searchCriteria);
        }
    }
}
